workflows:
  my_workflow:
    jobs:
      - install
      - test
      - lint
      - end_to_end
      - documentation:
          requires:
          - lint
          - end_to_end

version: 2.1
jobs:
  install:
    docker:
      - image: cimg/node:14.15.0 # the primary container, where your job's commands are run
        auth:
          username: xaela37
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install
      - save_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
          - node_modules #ça marche jusqu'ici pour l'instant
  test:
    docker:
      - image: cimg/node:14.15.0 # the primary container, where your job's commands are run
        auth:
          username: xaela37
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}
  lint:
    docker:
      - image: cimg/node:14.15.0 # the primary container, where your job's commands are run
        auth:
          username: xaela37
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}  
      - run:
          name: "step lint"
          command: |
            yarn lint
            yarn format:check
      - run:
          name: "yarn test"
          command: yarn test
  end_to_end:
    docker:
      - image: cimg/node:14.15.0
        auth:
          username: xaela37
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: xaela37
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: pguser
          POSTGRES_DB: pgdb
          POSTGRES_PASSWORD: pass
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "yarn test"
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://pguser:pass@localhost:5432/pgdb        
  documentation:
    docker:
      - image: cimg/node:14.15.0
        auth:
          username: xaela37
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: "yarn doc build"
          command: |
            yarn doc:build
            yarn add save-artifact-to-github
      - store_artifacts:
          path: docs        